networks:
  network_app:
    driver: bridge

services:
  ubuntu:
    container_name: ${APP_NAME}_ubuntu
    hostname: ubuntu
    build:
      context: ./.docker/ubuntu
      dockerfile: Dockerfile
    networks:
      - network_app
